export type Database = {
  public: {
    Tables: {
      Businesses: {
        Row: {
          id: string;
          business_name: string;
          slug: string;
          description: string | null;
          category: string | null;
          phone: string | null;
          spoken_languages: string[] | null;
          email: string | null;
          whatsapp: string | null;
          website: string | null;
          address: Record<string, unknown> | null;
          logo_url: string | null;
          images: unknown[] | null;
          hours: Record<string, unknown> | string | null;
          status: string | null;
          lifecycle_status: string | null;
          owner_id: string;
          created_at: string | null;
          updated_at: string | null;
          isretail: boolean | null;
          isrestaurant: boolean | null;
          isdealership: boolean | null;
          facebook: string | null;
          instagram: string | null;
          twitter: string | null;
          tiktok: string | null;
          lat: number | null;
          lon: number | null;
          admin_note: string | null;
          verified_info: Record<string, unknown> | null;
          note_history: Record<string, unknown>[] | null;
          plan: string;
          plan_expires_at: string | null;
          max_gallery_images: number;
          max_menu_items: number;
          max_retail_items: number;
          max_car_listings: number;
          allow_social_links: boolean;
          allow_whatsapp: boolean;
          allow_promoted: boolean;
          allow_reviews: boolean;
          allow_qr: boolean;
          plan_selected_at: string | null;
          claimed_at: string | null;
          trial_start: string | null;
          trial_end: string | null;
          is_archived: boolean;
          moderation_status: string | null;
          profile_theme: string;
          profile_template: string;
          theme: string;
          accent_color: string | null;
        };
      };
    };
  };
};
