export const supportedLanguages = [
    { code: 'auto', name: 'Auto (Detect)', emoji: '🌍' },
    { code: 'am', name: 'Amharic', emoji: '🇪🇹' },
    { code: 'ar', name: 'Arabic', emoji: '🟩' }, // Arab League (green square)
    { code: 'az', name: 'Azerbaijani', emoji: '🇦🇿' },
    { code: 'bn', name: 'Bengali', emoji: '🇧🇩' },
    { code: 'de', name: 'German', emoji: '🇩🇪' },
    { code: 'el', name: 'Greek', emoji: '🇬🇷' },
    { code: 'en', name: 'English', emoji: '🇺🇸' },
    { code: 'es', name: 'Spanish', emoji: '🇪🇸' },
    { code: 'fa', name: 'Farsi (Persian)', emoji: '🇮🇷' },
    { code: 'fr', name: 'French', emoji: '🇫🇷' },
    { code: 'ha', name: 'Hausa', emoji: '🇳🇬' },
    { code: 'he', name: 'Hebrew', emoji: '🇮🇱' },
    { code: 'hi', name: 'Hindi', emoji: '🇮🇳' },
    { code: 'hy', name: 'Armenian', emoji: '🇦🇲' },
    { code: 'id', name: 'Indonesian', emoji: '🇮🇩' },
    { code: 'it', name: 'Italian', emoji: '🇮🇹' },
    { code: 'ja', name: 'Japanese', emoji: '🇯🇵' },
    { code: 'ka', name: 'Georgian', emoji: '🇬🇪' },
    { code: 'kk', name: 'Kazakh', emoji: '🇰🇿' },
    { code: 'ko', name: 'Korean', emoji: '🇰🇷' },
    { code: 'ku', name: 'Kurdish', emoji: '🇹🇯' }, // Same as ckb for now
    { code: 'ms', name: 'Malay', emoji: '🇲🇾' },
    { code: 'my', name: 'Burmese', emoji: '🇲🇲' },
    { code: 'ne', name: 'Nepali', emoji: '🇳🇵' },
    { code: 'pa', name: 'Punjabi', emoji: '🇮🇳' },
    { code: 'pl', name: 'Polish', emoji: '🇵🇱' },
    { code: 'ps', name: 'Pashto', emoji: '🇦🇫' },
    { code: 'pt', name: 'Portuguese', emoji: '🇵🇹' },
    { code: 'ro', name: 'Romanian', emoji: '🇷🇴' },
    { code: 'ru', name: 'Russian', emoji: '🇷🇺' },
    { code: 'so', name: 'Somali', emoji: '🇸🇴' },
    { code: 'sw', name: 'Swahili', emoji: '🇰🇪' },
    { code: 'ta', name: 'Tamil', emoji: '🇮🇳' },
    { code: 'th', name: 'Thai', emoji: '🇹🇭' },
    { code: 'tr', name: 'Turkish', emoji: '🇹🇷' },
    { code: 'ug', name: 'Uyghur', emoji: '🇨🇳' },
    { code: 'uk', name: 'Ukrainian', emoji: '🇺🇦' },
    { code: 'ur', name: 'Urdu', emoji: '🇵🇰' },
    { code: 'uz', name: 'Uzbek', emoji: '🇺🇿' },
    { code: 'vi', name: 'Vietnamese', emoji: '🇻🇳' },
    { code: 'zh', name: 'Chinese', emoji: '🇨🇳' },
  ];
  